apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checkpoint-restore-webhook
rules:
- apiGroups: ["migration.dcnlab.com"]   # 실제 CRD 그룹으로!
  resources: ["checkpointrestores"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]  # optional
  resources: ["pods"]
  verbs: ["get","list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: checkpoint-restore-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: checkpoint-restore-webhook
subjects:
- kind: ServiceAccount
  name: checkpoint-restore-webhook
  namespace: stateful-migration
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: checkpoint-restore-webhook
webhooks:
- name: image-mutate.checkpoint-restore.k8s
  admissionReviewVersions: ["v1"]
  sideEffects: None
  timeoutSeconds: 5
  failurePolicy: Ignore     # 초기엔 Ignore로; 안정화 후 Fail 권장
  clientConfig:
    service:
      name: checkpoint-restore-webhook-svc
      namespace: stateful-migration
      path: /mutate
      port: 443
    caBundle: <cabundle>
  - operations: ["CREATE"]
    apiGroups: [""]
    apiVersions: ["v1"]
    resources: ["pods"]
  matchPolicy: Equivalent

