apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- rbac.yaml
- deployment.yaml
- service.yaml

commonLabels:
  app.kubernetes.io/name: checkpoint-apiserver
  app.kubernetes.io/part-of: stateful-migration-operator

images:
- name: lehuannhatrang/stateful-migration-operator
  newName: lehuannhatrang/stateful-migration-operator
  newTag: apiserver-latest
