---
apiVersion: v1
kind: Secret
metadata:
  name: karmada-kubeconfig
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: karmada-config
type: Opaque
data:
  # Replace this with your base64-encoded karmada-apiserver kubeconfig
  # To encode: cat ~/.kube/karmada-apiserver-config | base64 -w 0
  kubeconfig: REPLACE_WITH_BASE64_ENCODED_KARMADA_KUBECONFIG 