apiVersion: v1
kind: Namespace
metadata:
  name: stateful-migration
  labels:
    app.kubernetes.io/name: stateful-migration-operator
    app.kubernetes.io/component: namespace
    control-plane: migration-backup-controller 