---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: migration-backup-controller
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: migration-backup-controller-role
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: rbac
rules:
# StatefulMigration resources
- apiGroups:
  - migration.dcnlab.com
  resources:
  - statefulmigrations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.dcnlab.com
  resources:
  - statefulmigrations/finalizers
  verbs:
  - update
- apiGroups:
  - migration.dcnlab.com
  resources:
  - statefulmigrations/status
  verbs:
  - get
  - patch
  - update
# CheckpointBackup resources
- apiGroups:
  - migration.dcnlab.com
  resources:
  - checkpointbackups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - migration.dcnlab.com
  resources:
  - checkpointbackups/finalizers
  verbs:
  - update
- apiGroups:
  - migration.dcnlab.com
  resources:
  - checkpointbackups/status
  verbs:
  - get
  - patch
  - update
# Core Kubernetes resources
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - patch
  - update
  - watch
# Namespaces for creating stateful-migration namespace
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
# Events for logging
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# Permissions to add labels to target resources
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - update
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - update
  - patch
# Events for logging
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
# Leader election
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
  - get
  - list
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: migration-backup-controller-rolebinding
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: migration-backup-controller-role
subjects:
- kind: ServiceAccount
  name: migration-backup-controller
  namespace: stateful-migration
---
# Leader election role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-backup-leader-election-role
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-backup-leader-election-rolebinding
  namespace: stateful-migration
  labels:
    app.kubernetes.io/name: migration-backup-controller
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: migration-backup-leader-election-role
subjects:
- kind: ServiceAccount
  name: migration-backup-controller
  namespace: stateful-migration 